"""Tests for higher-dimensional lifts of tetrahedral point clouds.

A recurring conjecture about structures with sharp algebraic conditions is that
they are three-dimensional *slices* or *projections* of something more symmetric
living in a higher dimension -- a cut-and-project quasicrystal, or a graph drawn
from a root system such as :math:`D_6` or :math:`E_8`.  Both readings are
falsifiable, and this module implements the tests.

Three independent obstructions are checked, each decisive on its own:

:func:`zmodule_rank`
    The rank of the :math:`\\mathbb{Z}`-module generated by the coordinates,
    computed in exact arithmetic.  A genuine cut-and-project set drawn from
    :math:`n` dimensions has rank :math:`n > 3` -- the icosahedral quasicrystals
    have rank 6, the dodecagonal ones rank 5 -- because its coordinates involve
    irrationals that are rationally independent.  A point set with rank exactly
    3 lies in a scaled copy of :math:`\\mathbb{Z}^3` and *is* a three-dimensional
    lattice structure; there is no higher-dimensional space for it to descend
    from.

:func:`edge_angle_spectrum`
    The set of angles between adjacent edge vectors.  In any root lattice the
    minimal vectors meet only at 60, 90, 120 or 180 degrees, because the inner
    product of two roots of norm 2 is an integer in ``{0, ±1, ±2}``.  A single
    angle outside that set rules out every root lattice at once, in every
    dimension.

:func:`root_system_report`
    Combines both, plus the coordination-number bound, into one verdict.

The tests are deliberately stated as *obstructions*: passing them would not
prove a lift exists, but failing any one of them proves none does.
"""

from __future__ import annotations

import logging
import math
from dataclasses import dataclass, field
from fractions import Fraction

import numpy as np
from numpy.typing import NDArray

__all__ = [
    "dodecagonal_quasilattice",
    "recognise_quadratic",
    "QuadraticForm",
    "ZModuleResult",
    "AngleSpectrum",
    "LiftReport",
    "zmodule_rank",
    "edge_angle_spectrum",
    "root_system_report",
    "ROOT_SYSTEM_KISSING",
    "ROOT_ANGLES_DEGREES",
]

LOGGER = logging.getLogger(__name__)

F64 = np.float64
FloatArray = NDArray[np.float64]

#: Kissing numbers (counts of minimal vectors) of the classical root lattices.
#: A graph whose vertices embed with every edge a minimal vector cannot have a
#: degree exceeding its host's kissing number.
ROOT_SYSTEM_KISSING: dict[str, int] = {
    "A3 = D3": 12,
    "D4": 24,
    "D5": 40,
    "D6": 60,
    "E6": 72,
    "E7": 126,
    "E8": 240,
}

#: The only angles two minimal vectors of a root lattice can subtend.  Roots
#: have norm 2 and integer inner products, so cos(theta) is in {0, ±1/2, ±1}.
ROOT_ANGLES_DEGREES: tuple[float, ...] = (60.0, 90.0, 120.0, 180.0)


# --------------------------------------------------------------------------- #
# Obstruction 1: the rank of the Z-module of coordinates
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class ZModuleResult:
    """Rank of the additive group generated by a point set's coordinates."""

    rank: int
    n_points: int
    ambient_dimension: int
    basis_size: int
    denominator: int | None

    @property
    def is_rational(self) -> bool:
        """Whether the coordinates needed no irrational basis elements."""
        return self.basis_size == 1

    @property
    def admits_projection_lift(self) -> bool:
        """Whether the rank leaves room for a higher-dimensional origin.

        A cut-and-project set from dimension ``n`` has coordinate rank ``n``.
        Rank equal to the ambient dimension means the set already *is* a
        lattice structure in that dimension, with nothing to project from.
        """
        return self.rank > self.ambient_dimension


def rational_coefficients(
    points: list[list[Fraction]],
) -> list[list[list[Fraction]]]:
    """Wrap purely rational coordinates as coefficients over the basis ``[1]``."""
    return [[[component] for component in point] for point in points]


@dataclass(frozen=True)
class QuadraticForm:
    """A recognised element ``p + q sqrt(d)`` of a real quadratic field."""

    rational: Fraction
    surd: Fraction
    radicand: int
    residual: float

    def value(self) -> float:
        return float(self.rational) + float(self.surd) * math.sqrt(self.radicand)

    def __str__(self) -> str:
        if self.surd == 0:
            return str(self.rational)
        sign = "-" if self.surd < 0 else "+"
        return f"{self.rational} {sign} {abs(self.surd)}*sqrt({self.radicand})"


def recognise_quadratic(
    value: float,
    radicand: int = 10,
    *,
    max_denominator: int = 200,
    max_surd_numerator: int = 400,
    tolerance: float = 1e-9,
) -> QuadraticForm | None:
    """Recognise a float as ``p + q sqrt(radicand)`` with small height.

    Used to turn a converged numerical optimum into exact coordinates.  A
    packing density such as the N = 2 phase's ``9/(139 - 40 sqrt 10)`` says which
    field the structure lives in; if the search has converged tightly enough, the
    individual lattice entries should be recognisable in that same field.

    The search is a direct one over a common denominator: for each ``d`` and each
    surd numerator ``b``, ``d*value - b*sqrt(radicand)`` must be within
    ``tolerance`` of an integer.  Returning ``None`` is meaningful -- it means the
    value is not a low-height element of this field, so either the optimum has
    not converged or the field guess is wrong.

    Parameters
    ----------
    value:
        The float to recognise.
    radicand:
        The ``d`` in ``sqrt(d)``.  Must be a positive non-square.
    max_denominator, max_surd_numerator:
        Height bounds on the search.
    tolerance:
        How close the rational part must land to an integer.

    Returns
    -------
    QuadraticForm or None
    """
    if radicand <= 0:
        raise ValueError("radicand must be positive")
    root = math.isqrt(radicand)
    if root * root == radicand:
        raise ValueError(f"radicand {radicand} is a perfect square")
    if not math.isfinite(value):
        raise ValueError("value must be finite")

    surd = math.sqrt(radicand)
    best: QuadraticForm | None = None
    for denominator in range(1, max_denominator + 1):
        scaled = denominator * value
        for numerator in range(-max_surd_numerator, max_surd_numerator + 1):
            rational_part = scaled - numerator * surd
            nearest = round(rational_part)
            residual = abs(rational_part - nearest) / denominator
            if residual < tolerance:
                candidate = QuadraticForm(
                    rational=Fraction(int(nearest), denominator),
                    surd=Fraction(numerator, denominator),
                    radicand=radicand,
                    residual=residual,
                )
                if best is None or residual < best.residual:
                    best = candidate
        if best is not None:
            return best
    return best


#: In-plane star vectors of the dodecagonal module, as exact coefficients over
#: the basis ``[1, sqrt(3)]``.  These are ``(cos(2 pi k / 12), sin(2 pi k / 12))``
#: for ``k = 0, 1, 2, 3``, which generate ``Z[zeta_12]`` as a rank-4 Z-module --
#: the minimal polynomial of ``zeta_12`` is ``x^4 - x^2 + 1``, of degree 4.
_DODECAGONAL_STAR: tuple[tuple[tuple[Fraction, Fraction], ...], ...] = (
    ((Fraction(1), Fraction(0)), (Fraction(0), Fraction(0))),                 # k=0
    ((Fraction(0), Fraction(1, 2)), (Fraction(1, 2), Fraction(0))),           # k=1
    ((Fraction(1, 2), Fraction(0)), (Fraction(0), Fraction(1, 2))),           # k=2
    ((Fraction(0), Fraction(0)), (Fraction(1), Fraction(0))),                 # k=3
)


def dodecagonal_quasilattice(
    window_radius: float = 1.6,
    index_range: int = 6,
    layers: int = 3,
    layer_spacing: Fraction = Fraction(1),
) -> tuple[FloatArray, list[list[list[Fraction]]]]:
    """A genuine dodecagonal cut-and-project quasicrystal, in float and exact form.

    Dodecagonal quasicrystals -- the symmetry class of the tetrahedron
    quasicrystal approximant of Haji-Akbari et al. -- are projections from five
    dimensions: four for the in-plane module ``Z[zeta_12]`` and one for the
    periodic stacking axis.  A point ``n`` in ``Z^4`` is accepted when its image
    under the *conjugate* star (Galois conjugation ``sqrt(3) -> -sqrt(3)``) falls
    inside the acceptance window, and the accepted points are projected by the
    physical star.

    This exists as a **positive control**.  The rank test in this module returns
    3 for every crystal here, which is a negative result; a test that can only
    ever return a negative is worthless.  Feeding it a structure whose lift is
    real and whose rank is known independently -- 5 -- shows the machinery is
    able to detect one.

    Parameters
    ----------
    window_radius:
        Radius of the circular acceptance window in perpendicular space.
    index_range:
        Integer range searched in each of the four module directions.
    layers:
        Number of periodic layers stacked along z.
    layer_spacing:
        Rational spacing between layers.

    Returns
    -------
    (points, coefficients)
        ``(n, 3)`` float coordinates, and the same points as exact coefficient
        vectors over the basis ``[1, sqrt(3)]`` suitable for :func:`zmodule_rank`.
    """
    if window_radius <= 0.0:
        raise ValueError("window_radius must be positive")
    if index_range < 1 or layers < 1:
        raise ValueError("index_range and layers must be >= 1")

    root3 = math.sqrt(3.0)
    physical: list[tuple[float, float]] = []
    exact: list[tuple[tuple[Fraction, Fraction], tuple[Fraction, Fraction]]] = []

    span = range(-index_range, index_range + 1)
    for n0 in span:
        for n1 in span:
            for n2 in span:
                for n3 in span:
                    counts = (n0, n1, n2, n3)
                    x_rat = sum(c * s[0][0] for c, s in zip(counts, _DODECAGONAL_STAR))
                    x_r3 = sum(c * s[0][1] for c, s in zip(counts, _DODECAGONAL_STAR))
                    y_rat = sum(c * s[1][0] for c, s in zip(counts, _DODECAGONAL_STAR))
                    y_r3 = sum(c * s[1][1] for c, s in zip(counts, _DODECAGONAL_STAR))

                    # Conjugate (perpendicular) image: sqrt(3) -> -sqrt(3).
                    perp_x = float(x_rat) - root3 * float(x_r3)
                    perp_y = float(y_rat) - root3 * float(y_r3)
                    if perp_x * perp_x + perp_y * perp_y > window_radius * window_radius:
                        continue

                    physical.append(
                        (
                            float(x_rat) + root3 * float(x_r3),
                            float(y_rat) + root3 * float(y_r3),
                        )
                    )
                    exact.append(((x_rat, x_r3), (y_rat, y_r3)))

    if not physical:
        raise ValueError("acceptance window selected no points; widen window_radius")

    points: list[list[float]] = []
    coefficients: list[list[list[Fraction]]] = []
    for layer in range(layers):
        height = layer_spacing * layer
        for (px, py), ((xr, x3), (yr, y3)) in zip(physical, exact):
            points.append([px, py, float(height)])
            coefficients.append([[xr, x3], [yr, y3], [height, Fraction(0)]])

    return np.ascontiguousarray(points, dtype=F64), coefficients


def zmodule_rank(
    coefficients: list[list[list[Fraction]]],
) -> ZModuleResult:
    """Rank of the Z-module generated by a point set's coordinates.

    Each coordinate is supplied not as a single number but as its exact
    *coefficient vector* over a chosen basis of real numbers that are linearly
    independent over the rationals -- for instance ``[1, sqrt(5)]``, so that
    the coordinate ``a + b*sqrt(5)`` is passed as ``[a, b]``.  This is what
    makes the test able to return an answer greater than the ambient dimension,
    and therefore able to detect a genuine lift rather than only ever denying
    one.

    A cut-and-project quasicrystal is exactly the case where the rank exceeds
    the ambient dimension: the icosahedral quasicrystals have rank 6 in 3-space
    and the dodecagonal ones rank 5, because their coordinates live in
    ``Q(sqrt 5)`` or ``Q(sqrt 3)`` and the two components are rationally
    independent.  A point set whose coordinates are all rational has basis
    ``[1]``, so its rank cannot exceed 3, and it is a three-dimensional lattice
    structure with no higher-dimensional space to descend from.

    Parameters
    ----------
    coefficients:
        ``[point][axis][basis_index]`` nested sequence of :class:`Fraction`.
        Use :func:`rational_coefficients` for purely rational input.

    Returns
    -------
    ZModuleResult
    """
    points = [[list(axis) for axis in point] for point in coefficients]
    if not points:
        raise ValueError("cannot compute the rank of an empty point set")

    ambient = len(points[0])
    if ambient == 0:
        raise ValueError("points must have at least one axis")
    basis_size = len(points[0][0])
    if basis_size == 0:
        raise ValueError("each coordinate needs at least one basis coefficient")
    for point in points:
        if len(point) != ambient or any(len(axis) != basis_size for axis in point):
            raise ValueError("every point must have the same shape")
    if not all(
        isinstance(c, Fraction) for point in points for axis in point for c in axis
    ):
        raise TypeError("coefficients must be exact Fractions, not floats")

    # Flatten (axis, basis) into one index: the module is generated inside
    # Q^(ambient * basis_size), and its rank is the rank of that matrix.
    flattened = [
        [component for axis in point for component in axis] for point in points
    ]

    denominator = 1
    for row in flattened:
        for component in row:
            denominator = denominator * component.denominator // math.gcd(
                denominator, component.denominator
            )

    integral = np.array(
        [[int(component * denominator) for component in row] for row in flattened],
        dtype=object,
    )
    rank = _integer_matrix_rank(integral)

    return ZModuleResult(
        rank=rank,
        n_points=len(points),
        ambient_dimension=ambient,
        basis_size=basis_size,
        denominator=denominator,
    )


def _integer_matrix_rank(matrix: NDArray[np.object_]) -> int:
    """Exact rank of an integer matrix by fraction-free Gaussian elimination.

    Python integers are unbounded, so this cannot lose precision the way a
    floating-point SVD would on the large numerators the common denominator
    produces.
    """
    rows = [list(map(Fraction, row)) for row in matrix.tolist()]
    n_cols = len(rows[0]) if rows else 0
    rank = 0

    for col in range(n_cols):
        pivot = next(
            (r for r in range(rank, len(rows)) if rows[r][col] != 0),
            None,
        )
        if pivot is None:
            continue
        rows[rank], rows[pivot] = rows[pivot], rows[rank]
        head = rows[rank]
        for r in range(len(rows)):
            if r != rank and rows[r][col] != 0:
                factor = rows[r][col] / head[col]
                rows[r] = [a - factor * b for a, b in zip(rows[r], head)]
        rank += 1
        if rank == len(rows):
            break
    return rank


# --------------------------------------------------------------------------- #
# Obstruction 2: angles between adjacent edges
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class AngleSpectrum:
    """Distinct angles subtended by adjacent edges of a unit-distance graph."""

    angles_degrees: FloatArray
    counts: NDArray[np.int64]
    n_adjacent_pairs: int
    tolerance_degrees: float

    @property
    def root_compatible(self) -> bool:
        """Whether every observed angle is one a root lattice permits."""
        return bool(
            all(
                any(abs(a - allowed) <= self.tolerance_degrees for allowed in ROOT_ANGLES_DEGREES)
                for a in self.angles_degrees
            )
        )

    @property
    def offending_angles(self) -> FloatArray:
        """Angles that no root lattice can realise."""
        mask = [
            not any(abs(a - allowed) <= self.tolerance_degrees for allowed in ROOT_ANGLES_DEGREES)
            for a in self.angles_degrees
        ]
        return self.angles_degrees[np.asarray(mask, dtype=bool)]


def edge_angle_spectrum(
    points: FloatArray,
    edges: NDArray[np.int64],
    *,
    tolerance_degrees: float = 1e-6,
    max_pairs: int = 2_000_000,
) -> AngleSpectrum:
    """Angles between pairs of edges meeting at a shared vertex.

    If the graph embeds in a root lattice with every edge a minimal vector,
    then any two edges sharing a vertex are two roots, and their inner product
    is an integer.  Normalised to unit edges this forces
    ``cos(theta) in {0, ±1/2, ±1}``, i.e. 60, 90, 120 or 180 degrees.  Any other
    angle is an obstruction valid in every dimension simultaneously, which is
    what makes this cheap test conclusive against :math:`D_6`, :math:`E_8` and
    everything else at once.

    Parameters
    ----------
    points:
        ``(n, 3)`` vertex coordinates.
    edges:
        ``(m, 2)`` vertex index pairs.
    tolerance_degrees:
        How close an angle must be to a permitted value to count as matching.
    max_pairs:
        Safety cap on the number of edge pairs examined.

    Returns
    -------
    AngleSpectrum
    """
    pts = np.ascontiguousarray(points, dtype=F64)
    edge_list = np.ascontiguousarray(edges, dtype=np.int64)
    if edge_list.ndim != 2 or edge_list.shape[1] != 2:
        raise ValueError(f"edges must have shape (m, 2), got {edge_list.shape}")

    incident: dict[int, list[int]] = {}
    for index, (a, b) in enumerate(edge_list):
        incident.setdefault(int(a), []).append(index)
        incident.setdefault(int(b), []).append(index)

    vectors = pts[edge_list[:, 1]] - pts[edge_list[:, 0]]
    norms = np.linalg.norm(vectors, axis=1)

    cosines: list[float] = []
    examined = 0
    for vertex, indices in incident.items():
        for i in range(len(indices)):
            for j in range(i + 1, len(indices)):
                ei, ej = indices[i], indices[j]
                # Orient both edges away from the shared vertex.
                vi = vectors[ei] if edge_list[ei, 0] == vertex else -vectors[ei]
                vj = vectors[ej] if edge_list[ej, 0] == vertex else -vectors[ej]
                cosines.append(float(vi @ vj / (norms[ei] * norms[ej])))
                examined += 1
                if examined >= max_pairs:
                    break
            if examined >= max_pairs:
                break
        if examined >= max_pairs:
            break

    if not cosines:
        return AngleSpectrum(
            angles_degrees=np.zeros(0, dtype=F64),
            counts=np.zeros(0, dtype=np.int64),
            n_adjacent_pairs=0,
            tolerance_degrees=tolerance_degrees,
        )

    degrees = np.degrees(np.arccos(np.clip(np.asarray(cosines, dtype=F64), -1.0, 1.0)))
    rounded = np.round(degrees, 6)
    unique, counts = np.unique(rounded, return_counts=True)

    return AngleSpectrum(
        angles_degrees=np.ascontiguousarray(unique, dtype=F64),
        counts=np.ascontiguousarray(counts, dtype=np.int64),
        n_adjacent_pairs=examined,
        tolerance_degrees=tolerance_degrees,
    )


# --------------------------------------------------------------------------- #
# Combined verdict
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class LiftReport:
    """Verdict on whether a point cloud can descend from a higher dimension."""

    zmodule: ZModuleResult
    angles: AngleSpectrum
    max_degree: int
    laplacian_multiplicities: dict[int, int] = field(default_factory=dict)

    @property
    def admissible_root_systems(self) -> list[str]:
        """Root lattices not already excluded by the coordination bound alone."""
        if not self.angles.root_compatible:
            return []
        return [
            name
            for name, kissing in ROOT_SYSTEM_KISSING.items()
            if kissing >= self.max_degree
        ]

    @property
    def verdict(self) -> str:
        reasons: list[str] = []
        if not self.zmodule.admits_projection_lift:
            reasons.append(
                f"coordinate Z-module has rank {self.zmodule.rank}, equal to the "
                f"ambient dimension, so the set is already a {self.zmodule.rank}D "
                "lattice structure and cannot be a projection from higher dimension"
            )
        if not self.angles.root_compatible:
            offenders = ", ".join(f"{a:.4f}" for a in self.angles.offending_angles[:4])
            reasons.append(
                f"edges meet at angles no root lattice permits ({offenders} deg; "
                "roots allow only 60/90/120/180)"
            )
        if not reasons:
            return "NO OBSTRUCTION FOUND — a lift is not excluded by these tests"
        return "LIFT EXCLUDED — " + "; ".join(reasons)


def root_system_report(
    exact_points: list[list[Fraction]],
    points: FloatArray,
    edges: NDArray[np.int64],
    *,
    multiplicities: dict[int, int] | None = None,
) -> LiftReport:
    """Run every obstruction test and return a combined verdict.

    Parameters
    ----------
    exact_points:
        The same point set in exact rational coordinates, for the rank test.
    points, edges:
        Floating-point coordinates and edge list, for the angle test.
    multiplicities:
        Optional Laplacian eigenvalue multiplicity histogram, carried through
        for comparison against irreducible representation dimensions.

    Returns
    -------
    LiftReport
    """
    zmodule = zmodule_rank(exact_points)
    angles = edge_angle_spectrum(points, edges)

    degrees = np.bincount(np.asarray(edges, dtype=np.int64).ravel())
    max_degree = int(degrees.max()) if degrees.size else 0

    report = LiftReport(
        zmodule=zmodule,
        angles=angles,
        max_degree=max_degree,
        laplacian_multiplicities=dict(multiplicities or {}),
    )
    LOGGER.info("lift verdict: %s", report.verdict)
    return report
